name: ğŸ Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"   # Se ejecuta cada 12 horas
  workflow_dispatch:          # Permite ejecuciÃ³n manual desde GitHub Actions
  push:
    branches:
      - main

jobs:
  build:
    name: Generar Snake
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§© Checkout del repositorio
        uses: actions/checkout@v3

      - name: ğŸ Generar animaciÃ³n de la culebra
        uses: Platane/snk@v3
        with:
          github_user_name: josetenorio30
          outputs: dist/github-contribution-grid-snake.svg

      - name: ğŸš€ Publicar animaciÃ³n
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
